# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='card',
        ),
    ]
