# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20171030_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cert',
            field=models.DateField(blank=True, null=True),
        ),
    ]
