# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_member_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='executions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='series',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/cristiano/django/arc_images/'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Execution',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Repetition',
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
